/*
 TidBits OoJs - version: 13.08.14-alpha
 README: https://github.com/najamelan/TidBits_Javascript_OoJs
*/
var TidBits=TidBits||{};
(function(w,n){function G(b,d,c,a,m){this.Static=d;this.IFace=m;this.Class=b[c];this.name=c;this.id=a;this.bases=[];this.layoutInstance=this.instanceLayout=this.staticLayout=null;this.inherited={staticLayout:!1,instanceLayout:!1};this.virtuals={};this.namespace=b}function x(b,d,c){this._this=b;this.classID=d;this.iFace=c;this.state={};this.supers=[];this.flags=0}function v(){return null}function H(b,d,e){function a(){}function m(){}var f=b[d];Object.defineProperty(a,"Public",{value:y});Object.defineProperty(a,
"Protected",{value:z});Object.defineProperty(a,"Private",{value:A});Object.defineProperty(a,"getPrivateInstance",{value:I});Object.defineProperty(a,"ooID",{value:q()});Object.defineProperty(f,"ooID",{value:a.ooID});Object.defineProperty(a,"toString",{value:function(){return"function Static(){ /*"+d+"*/ }"}});Object.defineProperty(f,"toString",{value:function(){return"function "+d+"()"}});k[a.ooID]=new G(b,a,d,a.ooID,m);c[a.ooID]=new x(a,a.ooID,f);r[d]=a.ooID;e!==n&&(f.prototype=Object.create(b[e].prototype),
k[a.ooID].bases=Array(e),r[e]&&c[a.ooID].supers.push(r[e]));Object.defineProperty(f.prototype,"constructor",{configurable:!0,value:f});Object.defineProperty(f.prototype,"Public",{configurable:!0,value:y});Object.defineProperty(f.prototype,"Protected",{configurable:!0,value:z});Object.defineProperty(f.prototype,"Private",{configurable:!0,value:A});Object.defineProperty(f.prototype,"Super",{configurable:!0,value:J});Object.defineProperty(f.prototype,"Virtual",{configurable:!0,value:K});m.prototype=
Object.create(f.prototype);return a}function y(){return s.call(this,arguments,h.PUBLIC)}function z(){s.call(this,arguments,h.PROTECTED)}function A(){s.call(this,arguments,h.PRIVATE)}function I(b){var d;return this!==k[c[this.ooID].classID].Static?null:(d=t(b.ooID,this.ooID))?c[d]._this:null}function L(b){return k[c[b.ooID].classID].name}function K(){s.call(this,arguments,h.VIRTUAL);var b=Array.prototype.slice.apply(arguments);b[b.length]=h.VIRTUAL;return b}function J(){if(c[this.ooID]&&0!==c[this.ooID].supers.length)throw Error("This object already has a parent. You have to call Super before calling Public or Protected.");
B.apply(this,arguments)}function B(){if(k[c[(this.prototype?this.prototype.constructor:this.constructor).ooID].classID].Static!==this){if(this.ooID===n){Object.defineProperty(this,"ooID",{value:q()});var b=new k[this.constructor.ooID].IFace;Object.defineProperty(b,"ooID",{value:this.ooID});c[this.ooID]=new x(this,this.constructor.ooID,b)}for(var b=k[c[this.ooID].classID],d,e=b.bases.length-1;0<=e;--e){var a=b.bases[e];r[a]&&0===c[this.ooID].supers.length&&(this[a]={},C.prototype=b.namespace[a].prototype,
d=new C(b.namespace[a],arguments),c[this.ooID].supers.push(d.ooID),M.call(c[d.ooID]._this),this[a]=d)}}}function M(){D.call(this,{instRec:c[this.ooID],layout:k[c[this.ooID].classID].instanceLayout,iFace:c[this.ooID].iFace},!0)}function C(b,c){return b.apply(this,c)}function s(b,d){B.apply(this);var e=k[c[this.ooID].classID].Static===this?"staticLayout":"instanceLayout",a={instRec:c[this.ooID],classID:c[this.ooID].classID,supers:c[this.ooID].supers,iFace:c[this.ooID].iFace,classMeta:k[c[this.ooID].classID],
virtuals:k[c[this.ooID].classID].virtuals,layout:k[c[this.ooID].classID][e],layoutTypeFlag:k[c[this.ooID].classID].Static===this?h.INHERITED_STATIC:h.INHERITED_INSTANCE,layoutType:e,accessLvl:d};if(!(a.instRec.flags&h.STORED)){c[this.ooID].flags|=h.STORED;var m=null===a.layout;m&&(a.layout=a.classMeta[a.layoutType]={});for(var f in this)this.hasOwnProperty(f)&&(m&&E(a.layout,f,null,h.PRIVATE,a.classID,!0),a.instRec.state[f]=this[f],delete this[f])}if(!a.classMeta.inherited[a.layoutType])for(a.classMeta.inherited[a.layoutType]=
!0,m=a.supers.length-1;0<=m;--m){f=k[c[a.supers[m]].classID][a.layoutType];var u=k[c[a.supers[m]].classID].virtuals,g;for(g in f)if(f.hasOwnProperty(g)&&!(f[g].flags&h.PRIVATE))if(a.layout[g]===n)a.layout[g]=f[g],a.layout[g].flags=f[g].flags&~h.VIRTUAL;else if(a.layout[g].ownerClass!==a.classID)throw Error("two baseclasses both provide member: "+g);for(var l in u)if(u.hasOwnProperty(l)&&(f[l]===n||f[l].flags&h.VIRTUAL)){a.virtuals[l]=[];for(var p in u[l])a.virtuals[l][a.virtuals[l].length]=u[l][p]}}if(null===
a.classMeta.layoutInstance||this.ooID===a.classMeta.layoutInstance)for("instanceLayout"===e&&(a.classMeta.layoutInstance=this.ooID),l=b.length-1;0<=l;--l)if(g=b[l],Array.isArray(g)&&g[g.length-1]===h.VIRTUAL)for(p=g.length-2;0<=p;--p)F.call(this,a,g[p]);else F.call(this,a,g);if("instanceLayout"===e)for(l=b.length-1;0<=l;--l)if(g=b[l],"function"===typeof g&&(g=/\W*function\W+([\w\$]+)\(/.exec(g.toString())[1],a.virtuals[g]!==n))for(p=a.virtuals[g].length-1;0<=p;--p)a.virtuals[g][p].ownerClass!==a.classID&&
N.call(this,a,g,a.virtuals[g][p].ownerClass);h.VIRTUAL!==d&&D.call(this,a);if(d===h.PUBLIC&&"instanceLayout"===e)return c[this.ooID].iFace}function F(b,c){var e="function"===typeof c?c:null,a="string"===typeof c?c:/\W*function\W+([\w\$]+)\(/.exec(c.toString())[1];b.layout[a]!==n&&(b.instRec.iFace[a]!==n&&!(b.accessLvl&h.PUBLIC)&&b.layout[a].flags&h.PUBLIC)&&delete b.instRec.iFace[a];if(b.layout[a]!==n&&e&&b.layout[a].ownerClass!==b.classID||b.layout[a]===n&&e)E(b.layout,a,e,b.accessLvl,b.classID,
!1);else if(b.layout[a]!==n)b.layout[a].flags=b.accessLvl|b.layout[a].flags&h.VIRTUAL;else throw Error("Couldn't find definition of member: "+a+" in class: "+b.classMeta.name);b.accessLvl&h.VIRTUAL&&(b.virtuals[a]=b.virtuals[a]||[],b.virtuals[a].push(b.layout[a]))}function N(b,d,e){e=t(this.ooID,e);delete c[e]._this[d];Object.defineProperty(c[e]._this,d,{enumerable:!0,configurable:!0,get:function(a,b){return function(){return a.bind(b)}}(b.layout[d].reference,this)})}function D(b,d){var e=Object.defineProperty,
a;for(a in b.layout)if(b.layout.hasOwnProperty(a)){var m=b.layout[a],f=m.reference,k;k=!0===d?m.flags&h.PROTECTED?[b.iFace]:[]:m.flags&h.PUBLIC?[this,b.iFace]:[this];for(var g=k.length-1;0<=g;--g){var l=t(this.ooID,m.ownerClass);f?e(k[g],a,{enumerable:!0,configurable:!0,get:function(a,b){return function(){return a.bind(b)}}(f,c[l]._this)}):e(k[g],a,{enumerable:!0,configurable:!0,get:function(a,b){return function(){return c[b].state[a]}}(a,l),set:function(a,b){return function(d){c[b].state[a]=d}}(a,
l)})}}}function t(b,d){if(c[b].classID===d)return b;for(var e=null,a,h=c[b].supers.length-1;a=c[b].supers[h];--h)if(a.classID===d){e=a;break}else if(null!==(e=t(a,d)))break;return e}function E(b,c,e,a,h,f){if(b[c]!==n&&f)throw Error("Property '"+c+"' is already defined");b[c]={flags:a,reference:e,ownerClass:h}}function q(){q.counter=q.counter||0;return++q.counter}if(!w.OoJs){w.OoJs=v;var k={},c={},r={},h={PRIVATE:1,PROTECTED:2,PUBLIC:4,VIRTUAL:8,INHERITED_INSTANCE:16,INHERITED_STATIC:32,STORED:64};
v.setupClass=H;v.typeOf=L}})(TidBits);"undefined"!==typeof module&&(module.exports.OoJs=TidBits.OoJs);
