/*
 TidBits OoJs - version: 13.08.20-alpha
 README: https://github.com/najamelan/TidBits_Javascript_OoJs
*/
var TidBits=TidBits||{};
(function(v){function F(b,d,c,a,m){this.Static=d;this.IFace=m;this.Class=b[c];this.name=c;this.id=a;this.bases=[];this.layoutInstance=this.instanceLayout=this.staticLayout=null;this.inherited={staticLayout:!1,instanceLayout:!1};this.virtuals={};this.namespace=b}function w(b,d,c){this._this=b;this.classID=d;this.iFace=c;this.state={};this.supers=[];this.flags=0}function u(){return null}function G(b,d,e){function a(){}function m(){}var f=b[d];Object.defineProperty(a,"Public",{value:x});Object.defineProperty(a,
"Protected",{value:y});Object.defineProperty(a,"Private",{value:z});Object.defineProperty(a,"getPrivateInstance",{value:H});Object.defineProperty(a,"ooID",{value:p()});Object.defineProperty(f,"ooID",{value:a.ooID});Object.defineProperty(a,"toString",{value:function(){return"function Static(){ /*"+d+"*/ }"}});Object.defineProperty(f,"toString",{value:function(){return"function "+d+"()"}});k[a.ooID]=new F(b,a,d,a.ooID,m);c[a.ooID]=new w(a,a.ooID,f);q[d]=a.ooID;"undefined"!==typeof e&&(f.prototype=Object.create(b[e].prototype),
k[a.ooID].bases=Array(e),q[e]&&c[a.ooID].supers.push(q[e]));Object.defineProperty(f.prototype,"constructor",{configurable:!0,value:f});Object.defineProperty(f.prototype,"Public",{configurable:!0,value:x});Object.defineProperty(f.prototype,"Protected",{configurable:!0,value:y});Object.defineProperty(f.prototype,"Private",{configurable:!0,value:z});Object.defineProperty(f.prototype,"Super",{configurable:!0,value:I});Object.defineProperty(f.prototype,"Virtual",{configurable:!0,value:J});m.prototype=
Object.create(f.prototype);return a}function x(){return r.call(this,arguments,h.PUBLIC)}function y(){r.call(this,arguments,h.PROTECTED)}function z(){r.call(this,arguments,h.PRIVATE)}function H(b){var d;return this!==k[c[this.ooID].classID].Static?null:(d=s(b.ooID,this.ooID))?c[d]._this:null}function K(b){return k[c[b.ooID].classID].name}function J(){r.call(this,arguments,h.VIRTUAL);var b=Array.prototype.slice.apply(arguments);b[b.length]=h.VIRTUAL;return b}function I(){if(c[this.ooID]&&0!==c[this.ooID].supers.length)throw Error("This object already has a parent. You have to call Super before calling Public or Protected.");
A.apply(this,arguments)}function A(){if(k[c[(this.prototype?this.prototype.constructor:this.constructor).ooID].classID].Static!==this){if("undefined"===typeof this.ooID){Object.defineProperty(this,"ooID",{value:p()});var b=new k[this.constructor.ooID].IFace;Object.defineProperty(b,"ooID",{value:this.ooID});c[this.ooID]=new w(this,this.constructor.ooID,b)}for(var b=k[c[this.ooID].classID],d,e=b.bases.length-1;0<=e;--e){var a=b.bases[e];q[a]&&0===c[this.ooID].supers.length&&(this[a]={},B.prototype=
b.namespace[a].prototype,d=new B(b.namespace[a],arguments),c[this.ooID].supers.push(d.ooID),L.call(c[d.ooID]._this),this[a]=d)}}}function L(){C.call(this,{instRec:c[this.ooID],layout:k[c[this.ooID].classID].instanceLayout,iFace:c[this.ooID].iFace},!0)}function B(b,c){return b.apply(this,c)}function r(b,d){A.apply(this);var e=k[c[this.ooID].classID].Static===this?"staticLayout":"instanceLayout",a={instRec:c[this.ooID],classID:c[this.ooID].classID,supers:c[this.ooID].supers,iFace:c[this.ooID].iFace,
classMeta:k[c[this.ooID].classID],virtuals:k[c[this.ooID].classID].virtuals,layout:k[c[this.ooID].classID][e],layoutTypeFlag:k[c[this.ooID].classID].Static===this?h.INHERITED_STATIC:h.INHERITED_INSTANCE,layoutType:e,accessLvl:d};if(!(a.instRec.flags&h.STORED)){c[this.ooID].flags|=h.STORED;var m=null===a.layout;m&&(a.layout=a.classMeta[a.layoutType]={});for(var f in this)this.hasOwnProperty(f)&&(m&&D(a.layout,f,null,h.PRIVATE,a.classID,!0),a.instRec.state[f]=this[f],delete this[f])}if(!a.classMeta.inherited[a.layoutType])for(a.classMeta.inherited[a.layoutType]=
!0,m=a.supers.length-1;0<=m;--m){f=k[c[a.supers[m]].classID][a.layoutType];var t=k[c[a.supers[m]].classID].virtuals,g;for(g in f)if(f.hasOwnProperty(g)&&!(f[g].flags&h.PRIVATE))if("undefined"===typeof a.layout[g])a.layout[g]=f[g],a.layout[g].flags=f[g].flags&~h.VIRTUAL;else if(a.layout[g].ownerClass!==a.classID)throw Error("two baseclasses both provide member: "+g);for(var l in t)if(t.hasOwnProperty(l)&&("undefined"===typeof f[l]||f[l].flags&h.VIRTUAL)){a.virtuals[l]=[];for(var n in t[l])a.virtuals[l][a.virtuals[l].length]=
t[l][n]}}if(null===a.classMeta.layoutInstance||this.ooID===a.classMeta.layoutInstance)for("instanceLayout"===e&&(a.classMeta.layoutInstance=this.ooID),l=b.length-1;0<=l;--l)if(g=b[l],Array.isArray(g)&&g[g.length-1]===h.VIRTUAL)for(n=g.length-2;0<=n;--n)E.call(this,a,g[n]);else E.call(this,a,g);if("instanceLayout"===e)for(l=b.length-1;0<=l;--l)if(g=b[l],"function"===typeof g&&(g=/\W*function\W+([\w\$]+)\(/.exec(g.toString())[1],"undefined"!==typeof a.virtuals[g]))for(n=a.virtuals[g].length-1;0<=n;--n)a.virtuals[g][n].ownerClass!==
a.classID&&M.call(this,a,g,a.virtuals[g][n].ownerClass);h.VIRTUAL!==d&&C.call(this,a);if(d===h.PUBLIC&&"instanceLayout"===e)return c[this.ooID].iFace}function E(b,c){var e="function"===typeof c?c:null,a="string"===typeof c?c:/\W*function\W+([\w\$]+)\(/.exec(c.toString())[1];"undefined"!==typeof b.layout[a]&&("undefined"!==typeof b.instRec.iFace[a]&&!(b.accessLvl&h.PUBLIC)&&b.layout[a].flags&h.PUBLIC)&&delete b.instRec.iFace[a];if("undefined"!==typeof b.layout[a]&&e&&b.layout[a].ownerClass!==b.classID||
"undefined"===typeof b.layout[a]&&e)D(b.layout,a,e,b.accessLvl,b.classID,!1);else if("undefined"!==typeof b.layout[a])b.layout[a].flags=b.accessLvl|b.layout[a].flags&h.VIRTUAL;else throw Error("Couldn't find definition of member: "+a+" in class: "+b.classMeta.name);b.accessLvl&h.VIRTUAL&&(b.virtuals[a]=b.virtuals[a]||[],b.virtuals[a].push(b.layout[a]))}function M(b,d,e){e=s(this.ooID,e);delete c[e]._this[d];Object.defineProperty(c[e]._this,d,{enumerable:!0,configurable:!0,get:function(a,b){return function(){return a.bind(b)}}(b.layout[d].reference,
this)})}function C(b,d){var e=Object.defineProperty,a;for(a in b.layout)if(b.layout.hasOwnProperty(a)){var m=b.layout[a],f=m.reference,k;k=!0===d?m.flags&h.PROTECTED?[b.iFace]:[]:m.flags&h.PUBLIC?[this,b.iFace]:[this];for(var g=k.length-1;0<=g;--g){var l=s(this.ooID,m.ownerClass);f?e(k[g],a,{enumerable:!0,configurable:!0,get:function(a,b){return function(){return a.bind(b)}}(f,c[l]._this)}):e(k[g],a,{enumerable:!0,configurable:!0,get:function(a,b){return function(){return c[b].state[a]}}(a,l),set:function(a,
b){return function(d){c[b].state[a]=d}}(a,l)})}}}function s(b,d){if(c[b].classID===d)return b;for(var e=null,a,h=c[b].supers.length-1;a=c[b].supers[h];--h)if(a.classID===d){e=a;break}else if(null!==(e=s(a,d)))break;return e}function D(b,c,e,a,h,f){if("undefined"!==typeof b[c]&&f)throw Error("Property '"+c+"' is already defined");b[c]={flags:a,reference:e,ownerClass:h}}function p(){p.counter=p.counter||0;return++p.counter}if(!v.OoJs){v.OoJs=u;var k={},c={},q={},h={PRIVATE:1,PROTECTED:2,PUBLIC:4,VIRTUAL:8,
INHERITED_INSTANCE:16,INHERITED_STATIC:32,STORED:64};u.setupClass=G;u.typeOf=K}})(TidBits);"undefined"!==typeof module&&(module.exports.OoJs=TidBits.OoJs);
